[package]
name = "querylib"
description = "Rust query language"
version = "0.1.0"
authors = ["lemonxah <lemon.xah@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/lemonxah/querylib"
documentation = "https://docs.rs/querylib/0.1.0/querylib/"
repository = "https://github.com/lemonxah/querylib"

[dependencies]
bson = "1.0.0"
serde = "1.0.115"